- name: Set hostname
  hostname:
    name: "{{ hostname }}"

- name: Add localhost host entry
  lineinfile:
    path: /etc/hosts
    search_string: '127.0.0.1'
    line: "127.0.0.1 localhost.localdomain localhost"
    create: yes

- name: Add server host entry
  lineinfile:
    path: /etc/hosts
    search_string: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}"
    line: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }} {{ ansible_ssh_host }} {{ ansible_hostname }}" 

- name: Add EPEL Repositories
  dnf:
    name: epel-release
    state: present

- name: Update OS System
  dnf:
    name: "*"
    state: latest

- name: Check If swapfile Already Exists
  stat:
    path: /swapfile
  register: swapfile_stat

- name: Create swapfile
  command: fallocate -l 2G /swapfile
  when: not swapfile_stat.stat.exists

- name: Set Permissions On swapfile
  file:
    path: /swapfile
    owner: root
    group: root
    mode: 0600
  when: not swapfile_stat.stat.exists

- name: Format swapfile
  command: mkswap /swapfile
  when: not swapfile_stat.stat.exists

- name: Enable swapfile
  command: swapon /swapfile
  when: not swapfile_stat.stat.exists

- name: Ensure swapfile is in /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: "^/swapfile\\s+"
    line: "/swapfile none swap sw 0 0"
    state: present